export const NEW_TESTAMENT_BOOKS = [
  'MATTHEW', 'MARK', 'LUKE', 'JOHN', 'ACTS', 'ROMANS',
  'CORINTHIANS', 'CORINTHIANS', 'GALATIANS', 'EPHESIANS',
  'PHILIPPIANS', 'COLOSSIANS', 'THESSALONIANS', 'THESSALONIANS',
  'TIMOTHY', 'TIMOTHY', 'TITUS', 'PHILEMON', 'HEBREWS',
  'JAMES', 'PETER', 'PETER', 'JOHN', 'JOHN', 'JOHN',
  'JUDE', 'REVELATION'
];

// Increased grid size to accommodate longer words
export const GRID_SIZE = 20;